baseURL = "/"
languageCode = "en-us"
languageLang = "en"
title = "Pez's Labs"

# RSS, categories and tags disabled for an easy start
disableKinds = ["section", "taxonomy", "RSS"]

# Security configuration for Netlify environment variables
[security.funcs]
getenv = ['^HUGO_', '^CI$', '^CONTEXT$', '^URL$', '^DEPLOY_PRIME_URL$']

