baseURL = "/"
languageCode = "en-us"
languageLang = "en"
title = "Pez's Labs"

# RSS, categories and tags disabled for an easy start
disableKinds = ["section", "taxonomy", "RSS"]

# Security configuration for Netlify environment variables
[security.funcs]
getenv = ['^HUGO_', '^CI$', '^CONTEXT$', '^URL$', '^DEPLOY_PRIME_URL$']

# Build configuration for Tailwind CSS
[build]
  [build.buildStats]
    [build.buildStats.css]
      source = "assets/notwatching/hugo_stats\\.json"
      target = "css"
    [build.buildStats.postcss]
      source = "(postcss|tailwind)\\.config\\.js"
      target = "css"
  [build.module]
    [[build.module.mounts]]
      source = "assets"
      target = "assets"
    [[build.module.mounts]]
      disableWatch = true
      source = "hugo_stats.json"
      target = "assets/notwatching/hugo_stats.json"
